import React from 'react';

function Store() {
    return {
        Essential: [
            { word: "building ", pronunciation: "(bɪldɪŋ)", meaning: "Building is the process of making something.", example: "Building Lego cities and towns is the favorite activity of many kids." },
            { word: "audible", pronunciation: "(o de bel)", meaning: "able to be heard", example: "From across the room the teachr's voice was barely audible." },
            { word: "decrease", pronunciation: "(di kres')", meaning: "make orbecome less", example: "As the kept spending money, the amount he had saved decreased." },
            { word: "pledge", pronunciation: "(plej)", meaning: "promise", example: "Monte was reluctant to pledge his loyalty to his new girlfriend." },
            { word: "casual", pronunciation: "(kazh u el)", meaning: "happening by chance ; not planned or expected; not calling attention to itself", example: "." },
            { word: "data", pronunciation: "(dat' e)", meaning: "facts ; information", example: "The data about the bank robbery were given to the F.B.I" },
            { word: "qualify", pronunciation: "(kwal' e-fi)", meaning: "become fit ; show that you are able", example: "I am trying to qualify for the job that is now vacant." },
            { word: "typical", pronunciation: "(tip' e kel)", meaning: "usual ; of a kind", example: "The sinister character in the movie wore a typical costume, dark shirt, loud tie, and tight jacket." },
            { word: "talent", pronunciation: "(tal'ent)", meaning: "natural ability", example: "Medori's talent was noted when she was in first grade." },
            { word: "topic", pronunciation: "(tap' ik)", meaning: "subject that people think, write ,or talk about", example: "Predicting the weather is our favorite topic of conversation" },
            { word: "popular", pronunciation: "(pop' u lar)", meaning: "liked by most people", example: "The Beatles wrote many popular songs." },
            { word: "abandon", pronunciation: "(e ban' den)", meaning: "desert ; leave wuthout planning to come back ; quit ", example: "When Roy abandoned his family,  the police went looking for him." },
            { word: "keen", pronunciation: "(ken)", meaning: "sharp ; eager ; intense ; senstive", example: "he butcher's keen knife cut through the meat." },
            { word: "jealous", pronunciation: "(jel' es)", meaning: "afraid that the one you love might prefer someone else ; wanting what someone else has", example: "A detective  was hired by the jealous widow to find the boyfriend who had abandoned her." },
            { word: "tact", pronunciation: "(takt)", meaning: "ability to say the night thing", example: "My aunt never hurts anyone's feelings because she always uses tact." },
            { word: "oath", pronunciation: "(oth)", meaning: "a promise that something is true ; a curse ", example: "The president will take the oath of office tomarrow." },
            { word: "vacant", pronunciation: "(va' kent)", meaning: "empty ; not filled ", example: "I put my coat on that vacant seat." },
            { word: "hardship", pronunciation: "(hard' ship)", meaning: "something that is hard to bear ; difficulty ", example: "The fighter had to face many hardships before he became champion." },
            { word: "detect", pronunciation: "(di' tekt)", meaning: "find out ; discover", example: "Sam Spade detected that the importaant papers had vanished." },
            { word: "defect", pronunciation: "(di' fekt)", meaning: "fault ; that which is wrong", example: ".His theory of the formation of Our world was filled with defects" },
            { word: "thorough", pronunciation: "(ther' o)", meaning: "being all that is needed; complete", example: "The police made  a thorough search of the house after the crime had been reported." },
            { word: "amateur", pronunciation: "(am' e ter)", meaning: "personwho does something for pleasur, not for money of as a prefession", example: "After his song , Don was told that he wasn't good enough to be anything but an amateur." },
            { word: "security", pronunciation: "(si kyur'e te)", meaning: "freedom from danger , care, or fear,; feeling or condition of being safe", example: "Our janitor likes the secutiy of having all doors locked at night." },
            { word: "document", pronunciation: "(dok' u ment)", meaning: "something handwritten or printed that gives  information or proof of some fact", example: "We were reluctant to destroy important document." },
            { word: "urban", pronunciation: "(er' ben)", meaning: "of or having to do with cities or towns", example: "I plan to exchange my urban location for rural one." },
            { word: "gloomy", pronunciation: "(glu'mi)", meaning: " dark ; dim ; in low spririts", example: "My cousin gloomy becaause his best friend had moved away." },
            { word: "frank", pronunciation: "(frangk)", meaning: "free in expressing ones real thoughts, opinions one feelings ; not hiding what is in one's mind", example: "." },
            { word: "reveal", pronunciation: "(ri vel')", meaning: "make known", example: "The evidence was revealed only after hours of questioning." },
            { word: "urgent", pronunciation: "(er' jent)", meaning: "demanding immediate action or attention; important", example: "." },
            { word: "prohibit", pronunciation: "(pro' hib' it)", meaning: "forbid by law or authority", example: "Many homeowner prohibit other from walking on their praperty." },
            { word: "migrate", pronunciation: "(m i frat)", meaning: "move from one place to another", example: "The fruit pickers migrated to whenver they could find work." },
            { word: "vessel", pronunciation: "(ves' el)", meaning: "a ship ; a hollow container; tube containing body fluid", example: "." },
            { word: "presist", pronunciation: "(per sist')", meaning: "continue firmly; refuse to stop or be changed", example: "The humid weather presisted all summer." },
            { word: "gleam", pronunciation: "(fle m)", meaning: "a flash or beam of light", example: "A gleam of light shone trhough the prison wwindow." },
            { word: " molest", pronunciation: "(mə'lest)", meaning: " interfere with and trouble ; disturb", example: "the gand did a thorough job of molesting the  people in the park." },
            { word: "feeble", pronunciation: "(fe'bl)", meaning: "weak", example: "The feeble old man collapsed on the sidewalk." },
            { word: "cease", pronunciation: "(ses)", meaning: "stop", example: "Cease trying to do more than you can." },
            { word: "outlaw", pronunciation: "(out'lo)", meaning: " an exile ; an outcast ; a criminal ; to declare unlawful", example: " The best-known outlaw of the American West was jesse James." },
            { word: "promote", pronunciation: "(pre mot')", meaning: "raise in rank or importance ; help to grow and develp ; help to orgnize", example: "Students who pass the test will be promoted to the next grade." },
            { word: " excessive", pronunciation: "(ek ses' iv)", meaning: "too much ; too great ; extreme", example: "Numerous attempts have been made to outlaw jet planets that make excessive noise." },
            { word: "retain", pronunciation: "(ri tan')", meaning: "keep ; remember ; employ by payment of a fee", example: "China dishes have the unique quality of retaining heat longer than metal pans." },
            { word: "absurd", pronunciation: "(ab serd')", meaning: " plainly not true or sensible ; foolish", example: "It was absurd to believe the fisherman's tall tale." },
            { word: "pollute", pronunciation: "(pe loot')", meaning: "make dirty", example: "The Atlantic Ocean is in danger of becoming polluted" },
        ],
        Five0Four: [
            { word: "building ", pronunciation: "(bɪldɪŋ)", meaning: "Building is the process of making something.", example: "Building Lego cities and towns is the favorite activity of many kids." },
            { word: "audible", pronunciation: "(o de bel)", meaning: "able to be heard", example: "From across the room the teachr's voice was barely audible." },
            { word: "decrease", pronunciation: "(di kres')", meaning: "make orbecome less", example: "As the kept spending money, the amount he had saved decreased." },
            { word: "pledge", pronunciation: "(plej)", meaning: "promise", example: "Monte was reluctant to pledge his loyalty to his new girlfriend." },
            { word: "casual", pronunciation: "(kazh u el)", meaning: "happening by chance ; not planned or expected; not calling attention to itself", example: "." },
            { word: "data", pronunciation: "(dat' e)", meaning: "facts ; information", example: "The data about the bank robbery were given to the F.B.I" },
            { word: "qualify", pronunciation: "(kwal' e-fi)", meaning: "become fit ; show that you are able", example: "I am trying to qualify for the job that is now vacant." },
            { word: "typical", pronunciation: "(tip' e kel)", meaning: "usual ; of a kind", example: "The sinister character in the movie wore a typical costume, dark shirt, loud tie, and tight jacket." },
            { word: "talent", pronunciation: "(tal'ent)", meaning: "natural ability", example: "Medori's talent was noted when she was in first grade." },
            { word: "topic", pronunciation: "(tap' ik)", meaning: "subject that people think, write ,or talk about", example: "Predicting the weather is our favorite topic of conversation" },
            { word: "popular", pronunciation: "(pop' u lar)", meaning: "liked by most people", example: "The Beatles wrote many popular songs." },
            { word: "abandon", pronunciation: "(e ban' den)", meaning: "desert ; leave wuthout planning to come back ; quit ", example: "When Roy abandoned his family,  the police went looking for him." },
            { word: "keen", pronunciation: "(ken)", meaning: "sharp ; eager ; intense ; senstive", example: "he butcher's keen knife cut through the meat." },
            { word: "jealous", pronunciation: "(jel' es)", meaning: "afraid that the one you love might prefer someone else ; wanting what someone else has", example: "A detective  was hired by the jealous widow to find the boyfriend who had abandoned her." },
            { word: "tact", pronunciation: "(takt)", meaning: "ability to say the night thing", example: "My aunt never hurts anyone's feelings because she always uses tact." },
            { word: "oath", pronunciation: "(oth)", meaning: "a promise that something is true ; a curse ", example: "The president will take the oath of office tomarrow." },
            { word: "vacant", pronunciation: "(va' kent)", meaning: "empty ; not filled ", example: "I put my coat on that vacant seat." },
            { word: "hardship", pronunciation: "(hard' ship)", meaning: "something that is hard to bear ; difficulty ", example: "The fighter had to face many hardships before he became champion." },
            { word: "detect", pronunciation: "(di' tekt)", meaning: "find out ; discover", example: "Sam Spade detected that the importaant papers had vanished." },
            { word: "defect", pronunciation: "(di' fekt)", meaning: "fault ; that which is wrong", example: ".His theory of the formation of Our world was filled with defects" },
            { word: "thorough", pronunciation: "(ther' o)", meaning: "being all that is needed; complete", example: "The police made  a thorough search of the house after the crime had been reported." },
            { word: "amateur", pronunciation: "(am' e ter)", meaning: "personwho does something for pleasur, not for money of as a prefession", example: "After his song , Don was told that he wasn't good enough to be anything but an amateur." },
            { word: "security", pronunciation: "(si kyur'e te)", meaning: "freedom from danger , care, or fear,; feeling or condition of being safe", example: "Our janitor likes the secutiy of having all doors locked at night." },
            { word: "document", pronunciation: "(dok' u ment)", meaning: "something handwritten or printed that gives  information or proof of some fact", example: "We were reluctant to destroy important document." },
            { word: "urban", pronunciation: "(er' ben)", meaning: "of or having to do with cities or towns", example: "I plan to exchange my urban location for rural one." },
            { word: "gloomy", pronunciation: "(glu'mi)", meaning: " dark ; dim ; in low spririts", example: "My cousin gloomy becaause his best friend had moved away." },
            { word: "frank", pronunciation: "(frangk)", meaning: "free in expressing ones real thoughts, opinions one feelings ; not hiding what is in one's mind", example: "." },
            { word: "reveal", pronunciation: "(ri vel')", meaning: "make known", example: "The evidence was revealed only after hours of questioning." },
            { word: "urgent", pronunciation: "(er' jent)", meaning: "demanding immediate action or attention; important", example: "." },
            { word: "prohibit", pronunciation: "(pro' hib' it)", meaning: "forbid by law or authority", example: "Many homeowner prohibit other from walking on their praperty." },
            { word: "migrate", pronunciation: "(m i frat)", meaning: "move from one place to another", example: "The fruit pickers migrated to whenver they could find work." },
            { word: "vessel", pronunciation: "(ves' el)", meaning: "a ship ; a hollow container; tube containing body fluid", example: "." },
            { word: "presist", pronunciation: "(per sist')", meaning: "continue firmly; refuse to stop or be changed", example: "The humid weather presisted all summer." },
            { word: "gleam", pronunciation: "(fle m)", meaning: "a flash or beam of light", example: "A gleam of light shone trhough the prison wwindow." },
            { word: " molest", pronunciation: "(mə'lest)", meaning: " interfere with and trouble ; disturb", example: "the gand did a thorough job of molesting the  people in the park." },
            { word: "feeble", pronunciation: "(fe'bl)", meaning: "weak", example: "The feeble old man collapsed on the sidewalk." },
            { word: "cease", pronunciation: "(ses)", meaning: "stop", example: "Cease trying to do more than you can." },
            { word: "outlaw", pronunciation: "(out'lo)", meaning: " an exile ; an outcast ; a criminal ; to declare unlawful", example: " The best-known outlaw of the American West was jesse James." },
            { word: "promote", pronunciation: "(pre mot')", meaning: "raise in rank or importance ; help to grow and develp ; help to orgnize", example: "Students who pass the test will be promoted to the next grade." },
            { word: " excessive", pronunciation: "(ek ses' iv)", meaning: "too much ; too great ; extreme", example: "Numerous attempts have been made to outlaw jet planets that make excessive noise." },
            { word: "retain", pronunciation: "(ri tan')", meaning: "keep ; remember ; employ by payment of a fee", example: "China dishes have the unique quality of retaining heat longer than metal pans." },
            { word: "absurd", pronunciation: "(ab serd')", meaning: " plainly not true or sensible ; foolish", example: "It was absurd to believe the fisherman's tall tale." },
            { word: "pollute", pronunciation: "(pe loot')", meaning: "make dirty", example: "The Atlantic Ocean is in danger of becoming polluted" },
        ],
        HighSchool: [
            { word: "building ", pronunciation: "(bɪldɪŋ)", meaning: "Building is the process of making something.", example: "Building Lego cities and towns is the favorite activity of many kids." },
            { word: "audible", pronunciation: "(o de bel)", meaning: "able to be heard", example: "From across the room the teachr's voice was barely audible." },
            { word: "decrease", pronunciation: "(di kres')", meaning: "make orbecome less", example: "As the kept spending money, the amount he had saved decreased." },
            { word: "pledge", pronunciation: "(plej)", meaning: "promise", example: "Monte was reluctant to pledge his loyalty to his new girlfriend." },
            { word: "casual", pronunciation: "(kazh u el)", meaning: "happening by chance ; not planned or expected; not calling attention to itself", example: "." },
            { word: "data", pronunciation: "(dat' e)", meaning: "facts ; information", example: "The data about the bank robbery were given to the F.B.I" },
            { word: "qualify", pronunciation: "(kwal' e-fi)", meaning: "become fit ; show that you are able", example: "I am trying to qualify for the job that is now vacant." },
            { word: "typical", pronunciation: "(tip' e kel)", meaning: "usual ; of a kind", example: "The sinister character in the movie wore a typical costume, dark shirt, loud tie, and tight jacket." },
            { word: "talent", pronunciation: "(tal'ent)", meaning: "natural ability", example: "Medori's talent was noted when she was in first grade." },
            { word: "topic", pronunciation: "(tap' ik)", meaning: "subject that people think, write ,or talk about", example: "Predicting the weather is our favorite topic of conversation" },
            { word: "popular", pronunciation: "(pop' u lar)", meaning: "liked by most people", example: "The Beatles wrote many popular songs." },
            { word: "abandon", pronunciation: "(e ban' den)", meaning: "desert ; leave wuthout planning to come back ; quit ", example: "When Roy abandoned his family,  the police went looking for him." },
            { word: "keen", pronunciation: "(ken)", meaning: "sharp ; eager ; intense ; senstive", example: "he butcher's keen knife cut through the meat." },
            { word: "jealous", pronunciation: "(jel' es)", meaning: "afraid that the one you love might prefer someone else ; wanting what someone else has", example: "A detective  was hired by the jealous widow to find the boyfriend who had abandoned her." },
            { word: "tact", pronunciation: "(takt)", meaning: "ability to say the night thing", example: "My aunt never hurts anyone's feelings because she always uses tact." },
            { word: "oath", pronunciation: "(oth)", meaning: "a promise that something is true ; a curse ", example: "The president will take the oath of office tomarrow." },
            { word: "vacant", pronunciation: "(va' kent)", meaning: "empty ; not filled ", example: "I put my coat on that vacant seat." },
            { word: "hardship", pronunciation: "(hard' ship)", meaning: "something that is hard to bear ; difficulty ", example: "The fighter had to face many hardships before he became champion." },
            { word: "detect", pronunciation: "(di' tekt)", meaning: "find out ; discover", example: "Sam Spade detected that the importaant papers had vanished." },
            { word: "defect", pronunciation: "(di' fekt)", meaning: "fault ; that which is wrong", example: ".His theory of the formation of Our world was filled with defects" },
            { word: "thorough", pronunciation: "(ther' o)", meaning: "being all that is needed; complete", example: "The police made  a thorough search of the house after the crime had been reported." },
            { word: "amateur", pronunciation: "(am' e ter)", meaning: "personwho does something for pleasur, not for money of as a prefession", example: "After his song , Don was told that he wasn't good enough to be anything but an amateur." },
            { word: "security", pronunciation: "(si kyur'e te)", meaning: "freedom from danger , care, or fear,; feeling or condition of being safe", example: "Our janitor likes the secutiy of having all doors locked at night." },
            { word: "document", pronunciation: "(dok' u ment)", meaning: "something handwritten or printed that gives  information or proof of some fact", example: "We were reluctant to destroy important document." },
            { word: "urban", pronunciation: "(er' ben)", meaning: "of or having to do with cities or towns", example: "I plan to exchange my urban location for rural one." },
            { word: "gloomy", pronunciation: "(glu'mi)", meaning: " dark ; dim ; in low spririts", example: "My cousin gloomy becaause his best friend had moved away." },
            { word: "frank", pronunciation: "(frangk)", meaning: "free in expressing ones real thoughts, opinions one feelings ; not hiding what is in one's mind", example: "." },
            { word: "reveal", pronunciation: "(ri vel')", meaning: "make known", example: "The evidence was revealed only after hours of questioning." },
            { word: "urgent", pronunciation: "(er' jent)", meaning: "demanding immediate action or attention; important", example: "." },
            { word: "prohibit", pronunciation: "(pro' hib' it)", meaning: "forbid by law or authority", example: "Many homeowner prohibit other from walking on their praperty." },
            { word: "migrate", pronunciation: "(m i frat)", meaning: "move from one place to another", example: "The fruit pickers migrated to whenver they could find work." },
            { word: "vessel", pronunciation: "(ves' el)", meaning: "a ship ; a hollow container; tube containing body fluid", example: "." },
            { word: "presist", pronunciation: "(per sist')", meaning: "continue firmly; refuse to stop or be changed", example: "The humid weather presisted all summer." },
            { word: "gleam", pronunciation: "(fle m)", meaning: "a flash or beam of light", example: "A gleam of light shone trhough the prison wwindow." },
            { word: " molest", pronunciation: "(mə'lest)", meaning: " interfere with and trouble ; disturb", example: "the gand did a thorough job of molesting the  people in the park." },
            { word: "feeble", pronunciation: "(fe'bl)", meaning: "weak", example: "The feeble old man collapsed on the sidewalk." },
            { word: "cease", pronunciation: "(ses)", meaning: "stop", example: "Cease trying to do more than you can." },
            { word: "outlaw", pronunciation: "(out'lo)", meaning: " an exile ; an outcast ; a criminal ; to declare unlawful", example: " The best-known outlaw of the American West was jesse James." },
            { word: "promote", pronunciation: "(pre mot')", meaning: "raise in rank or importance ; help to grow and develp ; help to orgnize", example: "Students who pass the test will be promoted to the next grade." },
            { word: " excessive", pronunciation: "(ek ses' iv)", meaning: "too much ; too great ; extreme", example: "Numerous attempts have been made to outlaw jet planets that make excessive noise." },
            { word: "retain", pronunciation: "(ri tan')", meaning: "keep ; remember ; employ by payment of a fee", example: "China dishes have the unique quality of retaining heat longer than metal pans." },
            { word: "absurd", pronunciation: "(ab serd')", meaning: " plainly not true or sensible ; foolish", example: "It was absurd to believe the fisherman's tall tale." },
            { word: "pollute", pronunciation: "(pe loot')", meaning: "make dirty", example: "The Atlantic Ocean is in danger of becoming polluted" },
        ],
        IETLS: [
            { word: "building ", pronunciation: "(bɪldɪŋ)", meaning: "Building is the process of making something.", example: "Building Lego cities and towns is the favorite activity of many kids." },
            { word: "audible", pronunciation: "(o de bel)", meaning: "able to be heard", example: "From across the room the teachr's voice was barely audible." },
            { word: "decrease", pronunciation: "(di kres')", meaning: "make orbecome less", example: "As the kept spending money, the amount he had saved decreased." },
            { word: "pledge", pronunciation: "(plej)", meaning: "promise", example: "Monte was reluctant to pledge his loyalty to his new girlfriend." },
            { word: "casual", pronunciation: "(kazh u el)", meaning: "happening by chance ; not planned or expected; not calling attention to itself", example: "." },
            { word: "data", pronunciation: "(dat' e)", meaning: "facts ; information", example: "The data about the bank robbery were given to the F.B.I" },
            { word: "qualify", pronunciation: "(kwal' e-fi)", meaning: "become fit ; show that you are able", example: "I am trying to qualify for the job that is now vacant." },
            { word: "typical", pronunciation: "(tip' e kel)", meaning: "usual ; of a kind", example: "The sinister character in the movie wore a typical costume, dark shirt, loud tie, and tight jacket." },
            { word: "talent", pronunciation: "(tal'ent)", meaning: "natural ability", example: "Medori's talent was noted when she was in first grade." },
            { word: "topic", pronunciation: "(tap' ik)", meaning: "subject that people think, write ,or talk about", example: "Predicting the weather is our favorite topic of conversation" },
            { word: "popular", pronunciation: "(pop' u lar)", meaning: "liked by most people", example: "The Beatles wrote many popular songs." },
            { word: "abandon", pronunciation: "(e ban' den)", meaning: "desert ; leave wuthout planning to come back ; quit ", example: "When Roy abandoned his family,  the police went looking for him." },
            { word: "keen", pronunciation: "(ken)", meaning: "sharp ; eager ; intense ; senstive", example: "he butcher's keen knife cut through the meat." },
            { word: "jealous", pronunciation: "(jel' es)", meaning: "afraid that the one you love might prefer someone else ; wanting what someone else has", example: "A detective  was hired by the jealous widow to find the boyfriend who had abandoned her." },
            { word: "tact", pronunciation: "(takt)", meaning: "ability to say the night thing", example: "My aunt never hurts anyone's feelings because she always uses tact." },
            { word: "oath", pronunciation: "(oth)", meaning: "a promise that something is true ; a curse ", example: "The president will take the oath of office tomarrow." },
            { word: "vacant", pronunciation: "(va' kent)", meaning: "empty ; not filled ", example: "I put my coat on that vacant seat." },
            { word: "hardship", pronunciation: "(hard' ship)", meaning: "something that is hard to bear ; difficulty ", example: "The fighter had to face many hardships before he became champion." },
            { word: "detect", pronunciation: "(di' tekt)", meaning: "find out ; discover", example: "Sam Spade detected that the importaant papers had vanished." },
            { word: "defect", pronunciation: "(di' fekt)", meaning: "fault ; that which is wrong", example: ".His theory of the formation of Our world was filled with defects" },
            { word: "thorough", pronunciation: "(ther' o)", meaning: "being all that is needed; complete", example: "The police made  a thorough search of the house after the crime had been reported." },
            { word: "amateur", pronunciation: "(am' e ter)", meaning: "personwho does something for pleasur, not for money of as a prefession", example: "After his song , Don was told that he wasn't good enough to be anything but an amateur." },
            { word: "security", pronunciation: "(si kyur'e te)", meaning: "freedom from danger , care, or fear,; feeling or condition of being safe", example: "Our janitor likes the secutiy of having all doors locked at night." },
            { word: "document", pronunciation: "(dok' u ment)", meaning: "something handwritten or printed that gives  information or proof of some fact", example: "We were reluctant to destroy important document." },
            { word: "urban", pronunciation: "(er' ben)", meaning: "of or having to do with cities or towns", example: "I plan to exchange my urban location for rural one." },
            { word: "gloomy", pronunciation: "(glu'mi)", meaning: " dark ; dim ; in low spririts", example: "My cousin gloomy becaause his best friend had moved away." },
            { word: "frank", pronunciation: "(frangk)", meaning: "free in expressing ones real thoughts, opinions one feelings ; not hiding what is in one's mind", example: "." },
            { word: "reveal", pronunciation: "(ri vel')", meaning: "make known", example: "The evidence was revealed only after hours of questioning." },
            { word: "urgent", pronunciation: "(er' jent)", meaning: "demanding immediate action or attention; important", example: "." },
            { word: "prohibit", pronunciation: "(pro' hib' it)", meaning: "forbid by law or authority", example: "Many homeowner prohibit other from walking on their praperty." },
            { word: "migrate", pronunciation: "(m i frat)", meaning: "move from one place to another", example: "The fruit pickers migrated to whenver they could find work." },
            { word: "vessel", pronunciation: "(ves' el)", meaning: "a ship ; a hollow container; tube containing body fluid", example: "." },
            { word: "presist", pronunciation: "(per sist')", meaning: "continue firmly; refuse to stop or be changed", example: "The humid weather presisted all summer." },
            { word: "gleam", pronunciation: "(fle m)", meaning: "a flash or beam of light", example: "A gleam of light shone trhough the prison wwindow." },
            { word: " molest", pronunciation: "(mə'lest)", meaning: " interfere with and trouble ; disturb", example: "the gand did a thorough job of molesting the  people in the park." },
            { word: "feeble", pronunciation: "(fe'bl)", meaning: "weak", example: "The feeble old man collapsed on the sidewalk." },
            { word: "cease", pronunciation: "(ses)", meaning: "stop", example: "Cease trying to do more than you can." },
            { word: "outlaw", pronunciation: "(out'lo)", meaning: " an exile ; an outcast ; a criminal ; to declare unlawful", example: " The best-known outlaw of the American West was jesse James." },
            { word: "promote", pronunciation: "(pre mot')", meaning: "raise in rank or importance ; help to grow and develp ; help to orgnize", example: "Students who pass the test will be promoted to the next grade." },
            { word: " excessive", pronunciation: "(ek ses' iv)", meaning: "too much ; too great ; extreme", example: "Numerous attempts have been made to outlaw jet planets that make excessive noise." },
            { word: "retain", pronunciation: "(ri tan')", meaning: "keep ; remember ; employ by payment of a fee", example: "China dishes have the unique quality of retaining heat longer than metal pans." },
            { word: "absurd", pronunciation: "(ab serd')", meaning: " plainly not true or sensible ; foolish", example: "It was absurd to believe the fisherman's tall tale." },
            { word: "pollute", pronunciation: "(pe loot')", meaning: "make dirty", example: "The Atlantic Ocean is in danger of becoming polluted" },
        ],
       TOEFL: [
            { word: "building ", pronunciation: "(bɪldɪŋ)", meaning: "Building is the process of making something.", example: "Building Lego cities and towns is the favorite activity of many kids." },
            { word: "audible", pronunciation: "(o de bel)", meaning: "able to be heard", example: "From across the room the teachr's voice was barely audible." },
            { word: "decrease", pronunciation: "(di kres')", meaning: "make orbecome less", example: "As the kept spending money, the amount he had saved decreased." },
            { word: "pledge", pronunciation: "(plej)", meaning: "promise", example: "Monte was reluctant to pledge his loyalty to his new girlfriend." },
            { word: "casual", pronunciation: "(kazh u el)", meaning: "happening by chance ; not planned or expected; not calling attention to itself", example: "." },
            { word: "data", pronunciation: "(dat' e)", meaning: "facts ; information", example: "The data about the bank robbery were given to the F.B.I" },
            { word: "qualify", pronunciation: "(kwal' e-fi)", meaning: "become fit ; show that you are able", example: "I am trying to qualify for the job that is now vacant." },
            { word: "typical", pronunciation: "(tip' e kel)", meaning: "usual ; of a kind", example: "The sinister character in the movie wore a typical costume, dark shirt, loud tie, and tight jacket." },
            { word: "talent", pronunciation: "(tal'ent)", meaning: "natural ability", example: "Medori's talent was noted when she was in first grade." },
            { word: "topic", pronunciation: "(tap' ik)", meaning: "subject that people think, write ,or talk about", example: "Predicting the weather is our favorite topic of conversation" },
            { word: "popular", pronunciation: "(pop' u lar)", meaning: "liked by most people", example: "The Beatles wrote many popular songs." },
            { word: "abandon", pronunciation: "(e ban' den)", meaning: "desert ; leave wuthout planning to come back ; quit ", example: "When Roy abandoned his family,  the police went looking for him." },
            { word: "keen", pronunciation: "(ken)", meaning: "sharp ; eager ; intense ; senstive", example: "he butcher's keen knife cut through the meat." },
            { word: "jealous", pronunciation: "(jel' es)", meaning: "afraid that the one you love might prefer someone else ; wanting what someone else has", example: "A detective  was hired by the jealous widow to find the boyfriend who had abandoned her." },
            { word: "tact", pronunciation: "(takt)", meaning: "ability to say the night thing", example: "My aunt never hurts anyone's feelings because she always uses tact." },
            { word: "oath", pronunciation: "(oth)", meaning: "a promise that something is true ; a curse ", example: "The president will take the oath of office tomarrow." },
            { word: "vacant", pronunciation: "(va' kent)", meaning: "empty ; not filled ", example: "I put my coat on that vacant seat." },
            { word: "hardship", pronunciation: "(hard' ship)", meaning: "something that is hard to bear ; difficulty ", example: "The fighter had to face many hardships before he became champion." },
            { word: "detect", pronunciation: "(di' tekt)", meaning: "find out ; discover", example: "Sam Spade detected that the importaant papers had vanished." },
            { word: "defect", pronunciation: "(di' fekt)", meaning: "fault ; that which is wrong", example: ".His theory of the formation of Our world was filled with defects" },
            { word: "thorough", pronunciation: "(ther' o)", meaning: "being all that is needed; complete", example: "The police made  a thorough search of the house after the crime had been reported." },
            { word: "amateur", pronunciation: "(am' e ter)", meaning: "personwho does something for pleasur, not for money of as a prefession", example: "After his song , Don was told that he wasn't good enough to be anything but an amateur." },
            { word: "security", pronunciation: "(si kyur'e te)", meaning: "freedom from danger , care, or fear,; feeling or condition of being safe", example: "Our janitor likes the secutiy of having all doors locked at night." },
            { word: "document", pronunciation: "(dok' u ment)", meaning: "something handwritten or printed that gives  information or proof of some fact", example: "We were reluctant to destroy important document." },
            { word: "urban", pronunciation: "(er' ben)", meaning: "of or having to do with cities or towns", example: "I plan to exchange my urban location for rural one." },
            { word: "gloomy", pronunciation: "(glu'mi)", meaning: " dark ; dim ; in low spririts", example: "My cousin gloomy becaause his best friend had moved away." },
            { word: "frank", pronunciation: "(frangk)", meaning: "free in expressing ones real thoughts, opinions one feelings ; not hiding what is in one's mind", example: "." },
            { word: "reveal", pronunciation: "(ri vel')", meaning: "make known", example: "The evidence was revealed only after hours of questioning." },
            { word: "urgent", pronunciation: "(er' jent)", meaning: "demanding immediate action or attention; important", example: "." },
            { word: "prohibit", pronunciation: "(pro' hib' it)", meaning: "forbid by law or authority", example: "Many homeowner prohibit other from walking on their praperty." },
            { word: "migrate", pronunciation: "(m i frat)", meaning: "move from one place to another", example: "The fruit pickers migrated to whenver they could find work." },
            { word: "vessel", pronunciation: "(ves' el)", meaning: "a ship ; a hollow container; tube containing body fluid", example: "." },
            { word: "presist", pronunciation: "(per sist')", meaning: "continue firmly; refuse to stop or be changed", example: "The humid weather presisted all summer." },
            { word: "gleam", pronunciation: "(fle m)", meaning: "a flash or beam of light", example: "A gleam of light shone trhough the prison wwindow." },
            { word: " molest", pronunciation: "(mə'lest)", meaning: " interfere with and trouble ; disturb", example: "the gand did a thorough job of molesting the  people in the park." },
            { word: "feeble", pronunciation: "(fe'bl)", meaning: "weak", example: "The feeble old man collapsed on the sidewalk." },
            { word: "cease", pronunciation: "(ses)", meaning: "stop", example: "Cease trying to do more than you can." },
            { word: "outlaw", pronunciation: "(out'lo)", meaning: " an exile ; an outcast ; a criminal ; to declare unlawful", example: " The best-known outlaw of the American West was jesse James." },
            { word: "promote", pronunciation: "(pre mot')", meaning: "raise in rank or importance ; help to grow and develp ; help to orgnize", example: "Students who pass the test will be promoted to the next grade." },
            { word: " excessive", pronunciation: "(ek ses' iv)", meaning: "too much ; too great ; extreme", example: "Numerous attempts have been made to outlaw jet planets that make excessive noise." },
            { word: "retain", pronunciation: "(ri tan')", meaning: "keep ; remember ; employ by payment of a fee", example: "China dishes have the unique quality of retaining heat longer than metal pans." },
            { word: "absurd", pronunciation: "(ab serd')", meaning: " plainly not true or sensible ; foolish", example: "It was absurd to believe the fisherman's tall tale." },
            { word: "pollute", pronunciation: "(pe loot')", meaning: "make dirty", example: "The Atlantic Ocean is in danger of becoming polluted" },
        ],
       University: [
            { word: "building ", pronunciation: "(bɪldɪŋ)", meaning: "Building is the process of making something.", example: "Building Lego cities and towns is the favorite activity of many kids." },
            { word: "audible", pronunciation: "(o de bel)", meaning: "able to be heard", example: "From across the room the teachr's voice was barely audible." },
            { word: "decrease", pronunciation: "(di kres')", meaning: "make orbecome less", example: "As the kept spending money, the amount he had saved decreased." },
            { word: "pledge", pronunciation: "(plej)", meaning: "promise", example: "Monte was reluctant to pledge his loyalty to his new girlfriend." },
            { word: "casual", pronunciation: "(kazh u el)", meaning: "happening by chance ; not planned or expected; not calling attention to itself", example: "." },
            { word: "data", pronunciation: "(dat' e)", meaning: "facts ; information", example: "The data about the bank robbery were given to the F.B.I" },
            { word: "qualify", pronunciation: "(kwal' e-fi)", meaning: "become fit ; show that you are able", example: "I am trying to qualify for the job that is now vacant." },
            { word: "typical", pronunciation: "(tip' e kel)", meaning: "usual ; of a kind", example: "The sinister character in the movie wore a typical costume, dark shirt, loud tie, and tight jacket." },
            { word: "talent", pronunciation: "(tal'ent)", meaning: "natural ability", example: "Medori's talent was noted when she was in first grade." },
            { word: "topic", pronunciation: "(tap' ik)", meaning: "subject that people think, write ,or talk about", example: "Predicting the weather is our favorite topic of conversation" },
            { word: "popular", pronunciation: "(pop' u lar)", meaning: "liked by most people", example: "The Beatles wrote many popular songs." },
            { word: "abandon", pronunciation: "(e ban' den)", meaning: "desert ; leave wuthout planning to come back ; quit ", example: "When Roy abandoned his family,  the police went looking for him." },
            { word: "keen", pronunciation: "(ken)", meaning: "sharp ; eager ; intense ; senstive", example: "he butcher's keen knife cut through the meat." },
            { word: "jealous", pronunciation: "(jel' es)", meaning: "afraid that the one you love might prefer someone else ; wanting what someone else has", example: "A detective  was hired by the jealous widow to find the boyfriend who had abandoned her." },
            { word: "tact", pronunciation: "(takt)", meaning: "ability to say the night thing", example: "My aunt never hurts anyone's feelings because she always uses tact." },
            { word: "oath", pronunciation: "(oth)", meaning: "a promise that something is true ; a curse ", example: "The president will take the oath of office tomarrow." },
            { word: "vacant", pronunciation: "(va' kent)", meaning: "empty ; not filled ", example: "I put my coat on that vacant seat." },
            { word: "hardship", pronunciation: "(hard' ship)", meaning: "something that is hard to bear ; difficulty ", example: "The fighter had to face many hardships before he became champion." },
            { word: "detect", pronunciation: "(di' tekt)", meaning: "find out ; discover", example: "Sam Spade detected that the importaant papers had vanished." },
            { word: "defect", pronunciation: "(di' fekt)", meaning: "fault ; that which is wrong", example: ".His theory of the formation of Our world was filled with defects" },
            { word: "thorough", pronunciation: "(ther' o)", meaning: "being all that is needed; complete", example: "The police made  a thorough search of the house after the crime had been reported." },
            { word: "amateur", pronunciation: "(am' e ter)", meaning: "personwho does something for pleasur, not for money of as a prefession", example: "After his song , Don was told that he wasn't good enough to be anything but an amateur." },
            { word: "security", pronunciation: "(si kyur'e te)", meaning: "freedom from danger , care, or fear,; feeling or condition of being safe", example: "Our janitor likes the secutiy of having all doors locked at night." },
            { word: "document", pronunciation: "(dok' u ment)", meaning: "something handwritten or printed that gives  information or proof of some fact", example: "We were reluctant to destroy important document." },
            { word: "urban", pronunciation: "(er' ben)", meaning: "of or having to do with cities or towns", example: "I plan to exchange my urban location for rural one." },
            { word: "gloomy", pronunciation: "(glu'mi)", meaning: " dark ; dim ; in low spririts", example: "My cousin gloomy becaause his best friend had moved away." },
            { word: "frank", pronunciation: "(frangk)", meaning: "free in expressing ones real thoughts, opinions one feelings ; not hiding what is in one's mind", example: "." },
            { word: "reveal", pronunciation: "(ri vel')", meaning: "make known", example: "The evidence was revealed only after hours of questioning." },
            { word: "urgent", pronunciation: "(er' jent)", meaning: "demanding immediate action or attention; important", example: "." },
            { word: "prohibit", pronunciation: "(pro' hib' it)", meaning: "forbid by law or authority", example: "Many homeowner prohibit other from walking on their praperty." },
            { word: "migrate", pronunciation: "(m i frat)", meaning: "move from one place to another", example: "The fruit pickers migrated to whenver they could find work." },
            { word: "vessel", pronunciation: "(ves' el)", meaning: "a ship ; a hollow container; tube containing body fluid", example: "." },
            { word: "presist", pronunciation: "(per sist')", meaning: "continue firmly; refuse to stop or be changed", example: "The humid weather presisted all summer." },
            { word: "gleam", pronunciation: "(fle m)", meaning: "a flash or beam of light", example: "A gleam of light shone trhough the prison wwindow." },
            { word: " molest", pronunciation: "(mə'lest)", meaning: " interfere with and trouble ; disturb", example: "the gand did a thorough job of molesting the  people in the park." },
            { word: "feeble", pronunciation: "(fe'bl)", meaning: "weak", example: "The feeble old man collapsed on the sidewalk." },
            { word: "cease", pronunciation: "(ses)", meaning: "stop", example: "Cease trying to do more than you can." },
            { word: "outlaw", pronunciation: "(out'lo)", meaning: " an exile ; an outcast ; a criminal ; to declare unlawful", example: " The best-known outlaw of the American West was jesse James." },
            { word: "promote", pronunciation: "(pre mot')", meaning: "raise in rank or importance ; help to grow and develp ; help to orgnize", example: "Students who pass the test will be promoted to the next grade." },
            { word: " excessive", pronunciation: "(ek ses' iv)", meaning: "too much ; too great ; extreme", example: "Numerous attempts have been made to outlaw jet planets that make excessive noise." },
            { word: "retain", pronunciation: "(ri tan')", meaning: "keep ; remember ; employ by payment of a fee", example: "China dishes have the unique quality of retaining heat longer than metal pans." },
            { word: "absurd", pronunciation: "(ab serd')", meaning: " plainly not true or sensible ; foolish", example: "It was absurd to believe the fisherman's tall tale." },
            { word: "pollute", pronunciation: "(pe loot')", meaning: "make dirty", example: "The Atlantic Ocean is in danger of becoming polluted" },
        ]
    }
}

export default Store;